### PR TITLE
Cache poetry dependencies

### PR DESCRIPTION
**Pull request by ericboucher**

### CODE REVIEW

**Review by laurentS — COMMENTED** [review]
Nice! Maybe take the opportunity to update poetry to latest version?

**Comment by edgarrmondragon** [comment]
@ericboucher This is a nice addition! Does this mean that all jobs running for the same commit sha will reuse the cached `.venv` and any new commit will invalidate cache?

**Comment by ericboucher** [comment]
All commits with the same poetry.lock will use the same cache. Note that to be safe we create one cache per Python version to avoid edge cases

**Review by laurentS — APPROVED** [review]
LGTM!

**Pull request merged**
