### PR TITLE
chore: update dependencies

### PR DESCRIPTION
**Pull request by laurentS**
This PR updates dependencies, including the sdk to ~~0.27.0~~ 0.22.0.

Some are skipped as they do not support python 3.7 anymore. See #208

### CODE REVIEW

**Comment by ericboucher** [comment]
Tests are failing:

```
FAILED tap_github/tests/test_tap.py::test_last_state_message_is_valid - assert 'progress_markers' not in '{"type": "S...000Z"}}]}}}}'
  'progress_markers' is contained here:
  
```

**Comment by laurentS** [comment]
I've changed the `sdk` version to `v0.22.1` temporarily to confirm that tests are passing. See linked sdk issue for details on the problem this PR surfaced.

**Comment by laurentS** [comment]
I guess it's harmless to merge it as is, but there is also no emergency in the sense that I don't think the SDK upgrade `0.19 -> 0.22.1` brings any changes that this tap uses.
Let's keep this open until the sdk situation is clarified, it'll save us a bit of PR overhead :)

**Comment by kgpayne** [comment]
@laurentS @ericboucher I have a [PR](https://github.com/meltano/sdk/pull/1708) to fix this issue in the SDK, with tests passing here (above) when pointing at the PR branch. Will revert to `> 0.22.1` here for now and update you once the fix is released 🙂👍

**Comment by JohannesRudolph** [comment]
@laurentS any idea when this will land? I'm prepping a PR to fix incremental loading of the GH Actions (workflow_runs etc.) streams at https://github.com/meshcloud/tap-github/tree/feature/fix-actions-streams and based this off of your branch here.

**Comment by laurentS** [comment]
@JohannesRudolph I'm going to merge this as is, with the sdk updated to 0.22.1, and we can open a new PR to update to the latest sdk version when https://github.com/meltano/sdk/pull/1708 is merged.

**Pull request merged**
