### PR TITLE
Sleep until remaining requests are restored

### PR DESCRIPTION
**Pull request by edgarrmondragon**
Use `ratelimit` decorators to sleep and retry after being rate-limited.

### CODE REVIEW

**Comment by ericboucher** [comment]
@edgarrmondragon this should probably be built on top of #39

**Comment by ericboucher** [comment]
@edgarrmondragon #39 has been merge and updates the sdk as well. It should be a bit simpler to implement what you had in mind now :)

**Comment by edgarrmondragon** [comment]
Hi @ericboucher! I see #39 nicely avoids hitting rate limits. Do you think we should close this PR?

**Comment by ericboucher** [comment]
@edgarrmondragon in case we still don't have enough tokens, maybe we could have a "wait" mechanism that get's triggered if all the tokens have used all their credits.

Feel free to close this if you feel like #39 fixed the problem for your use case

**Comment by ericboucher** [comment]
Closing this for now as it got quite out of date. @edgarrmondragon feel free to reopen a PR if there is still a need :)

**Pull request closed without merging**
